name: Deploy

on:
  push:
    branches:
      - main
  pull_request: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go based on the go.mod file
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"

      - name: Build the application
        run: ./build.sh

      - name: Configure the AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/steam-game-prices-notifier-github-actions-role
      
      - name: Deploy the application
        run: |
          aws lambda update-function-code \
            --function-name steam-game-prices-notifier \
            --zip-file fileb://./function.zip
