name: Lint

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run the linter
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "-c ./.golangci.yaml"
          reporter: github-pr-review
