name: reviewdog

on:
  pull_request:

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run the linter
        uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
          fail_on_error: true
